build: false

platform:
- x86
- x64
  
environment:
  matrix:
    - CONDA: 2.7
    - CONDA: 3.6

init:
  - "ECHO %CONDA%"

install:
  - "set PATH=%CONDA%;%CONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install numpy scipy h5py matplotlib
  - activate test-environment
  - pip install fabio xfab pycifrw pillow --no-deps
  - pip install .

test_script:
  - cd test
  - python run_tests.py